from pathlib import Path
p=Path(r'c:\Users\Sumangala\Desktop\protothon\SakshaAI\report.html')
s=p.read_text(encoding='utf-8')
# counts
bq=s.count('`')
sq=s.count("'")
dq=s.count('"')
open_braces=s.count('{')
close_braces=s.count('}')
open_paren=s.count('(')
close_paren=s.count(')')
open_sq=s.count('[')
close_sq=s.count(']')
print('backticks',bq)
print("single_quotes",sq)
print('double_quotes',dq)
print('{',open_braces,'}',close_braces)
print('(',open_paren,')',close_paren)
print('[',open_sq,']',close_sq)
print('\n--- EOF preview ---')
print(s[-400:])
